[workspace]
resolver = "2"
members = [
    "c3p0_common",
    "c3p0_mongodb",
    "c3p0_sqlx",
    "c3p0",
]

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.69.1"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["mysql", "postgres", "pg", "sqlite", "json"]
authors = ["Francesco Cina <ufoscout@gmail.com>"]

[workspace.dependencies]
c3p0_common = { path = "./c3p0_common", version = "0.69.1" }
c3p0 = { path = "./c3p0", version = "0.69.1" }
c3p0_mongodb = { path = "./c3p0_mongodb", version = "0.69.1" }
c3p0_sqlx = { path = "./c3p0_sqlx", version = "0.69.1" }

rand = "0.8"
rustainers = "0.11"
testcontainers = { package = "testcontainers-modules", version = "0.3", features = ["mysql", "mongo", "postgres"] }
tokio = { version = "1" }
async-trait = "0.1"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
sqlx = { version = "0.7", default-features = false, features = [ "json" ] }
maybe-single = { version = "0.16", features =["tokio"] }
mongodb = { version = "2.0", features =["bson-uuid-1"] } 
once_cell = "1.5.0"
thiserror = "1.0"
uuid = { version = "1", features = ["serde", "v4"] }

anyhow = "1"
static_assertions = "1"

[profile.dev]
# debug = false

# Set the settings for all dependencies (but not this crate itself or any workspace member).
# This includes build dependencies.
# Level range is from 0 (default for dev) to 3 (default for release)
# [profile.dev.package."*"]
# opt-level = 1

# Set the settings for build scripts and proc-macros.
# [profile.dev.build-override]
# opt-level = 2