[workspace]
resolver = "2"
members = [
    "c3p0_common",
    "c3p0_in_memory",
    "c3p0_postgres",
    "c3p0_sqlx",
    "c3p0",
    "c3p0_tests_migrate",
]

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.68.0"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["mysql", "postgres", "pg", "sqlite", "json"]
authors = ["Francesco Cina <ufoscout@gmail.com>"]

[workspace.dependencies]
c3p0_common = { path = "./c3p0_common", version = "0.68.0" }
c3p0 = { path = "./c3p0", version = "0.68.0" }
c3p0_in_memory = { path = "./c3p0_in_memory", version = "0.68.0" }
#c3p0_mysql = { path = "./c3p0_mysql", version = "0.68.0" }
c3p0_postgres = { path = "./c3p0_postgres", version = "0.68.0" }
c3p0_sqlx = { path = "./c3p0_sqlx", version = "0.68.0" }

rand = "0.8"
testcontainers = { package = "testcontainers-modules", version = "0.1", features = ["mysql", "postgres"] }
tokio = { version = "1" }
async-trait = "0.1"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
sqlx = { version = "0.7", default-features = false, features = [ "json" ] }
deadpool = { version = "0.10", features = ["rt_tokio_1"] }
deadpool-postgres = "0.11" 
tokio-postgres = { version = "0.7", features = ["with-serde_json-1"] }
maybe-single = { version = "0.15.0", features =["async"] }
once_cell = "1.5.0"
thiserror = "1.0"

include_dir = { version = "0.7", default-features = false }
md-5 = { version = "0.10", default-features = false }
same-file = { version = "1" }
walkdir = { version = "2.3" }

anyhow = "1"
static_assertions = "1"
